### PR TITLE
Fix path to SDL

### PR DESCRIPTION
**Pull request by VVeremjova**
Now after starting with flag it will find and execute SDL bin

Relates to [APPLINK-23697](https://adc.luxoft.com/jira/browse/APPLINK-23697)

Please review @dtrunov, @OHerasym, @Kozoriz, @VProdanov @LuxoftAKutsan

### CODE REVIEW

**Comment by VProdanov** [comment]
Reviewed.

**Comment by OHerasym** [comment]
Reviewed.

**Comment by dtrunov** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@AGaliuzov please merge

**Pull request merged**
