### PR TITLE
Fix streaming and receiving notifications

### PR DESCRIPTION
**Pull request by Kozoriz**
When we skip all messages with timespan = 0, streaming not possible.
	Without subscribing to notification we will not get it.

### CODE REVIEW

**Comment by Kozoriz** [comment]
Please review : @okozlovlux, @LevchenkoS, @dev-gh, @anosach-luxoft , @VProdanov

**Comment by LevchenkoS** [comment]
@Kozoriz Reviewed.

**Comment by dev-gh** [comment]
Visually reviewed

**Comment by okozlovlux** [comment]
@Kozoriz reviewed

**Comment by VProdanov** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Pull request merged**
