### PR TITLE
Fix issues with bson linking

### PR DESCRIPTION
**Pull request by jacobkeeler**
Requires changes from https://github.com/smartdevicelink/bson_c_lib/pull/35

The CMake BSON installation was buggy after the merge of the Remote ATF feature. This makes the installation more consistent by:
1. Searching for the lua wrapper library in `FindBSON.cmake`
2. Follow normal lua library installation practices.

### CODE REVIEW

**Comment by dboltovskyi** [comment]
@jacobkeeler Please notice we have the following error when trying to build the ATF project from this PR:
```
-- Installing: /home/developer/sdl/b_atf/bin/ATF
CMake Error at cmake_install.cmake:73 (file):
  file INSTALL cannot find
  "/home/developer/sdl/b_atf/bin/lib/lua/5.2/bson4lua.so": No such file or
  directory.

```

**Comment by jacobkeeler** [comment]
@dboltovskyi Did you point to the changes in smartdevicelink/bson_c_lib#35?

**Comment by dboltovskyi** [comment]
@jacobkeeler That was the reason of the issue. Now project is buildable. Thanks!
However when I try run `018_V5_happy_path_SUCCESS.lua` script I got the following:
```
Lua error:
.../Security/SSLHandshakeFlow/018_V5_happy_path_SUCCESS.lua:12: module 'bson4lua' not found:
	no field package.preload['bson4lua']
	no file './modules/bson4lua.lua'
	no file './modules/atf/stdlib/bson4lua.lua'
	no file '/usr/local/share/lua/5.2/bson4lua.lua'
	no file '/usr/local/share/lua/5.2/bson4lua/init.lua'
	no file '/usr/local/lib/lua/5.2/bson4lua.lua'
	no file '/usr/local/lib/lua/5.2/bson4lua/init.lua'
	no file '/usr/share/lua/5.2/bson4lua.lua'
	no file '/usr/share/lua/5.2/bson4lua/init.lua'
	no file './bson4lua.lua'
	no file './lib/libbson4lua.so'
	no file './libbson4lua.so'
	no file '/usr/local/lib/lua/5.2/bson4lua.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/bson4lua.so'
	no file '/usr/lib/lua/5.2/bson4lua.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './bson4lua.so'
```
I suppose `bson4lua.so` should has `lib` prefix in it's name

**Comment by jacobkeeler** [comment]
Hmmm, a workaround could be to copy the library into the root of the build directory. Lua looks in very specific directories for these modules, I suppose I must have had the library normally installed when I was testing (in `/usr/local/lib`). I think the more consistent solution would be to install the bson library in `/usr/local/lib` by default (maybe through a 3rd party install prefix?).

**Comment by dboltovskyi** [comment]
Search patterns for the libraries are defined in https://github.com/smartdevicelink/sdl_atf/blob/10a8207e5b9676b37f6d7c341b991d54466d710e/src/lua_interpreter.cc#L81
So we can update this string in a following way:
```
lua_pushstring(lua_state, "./lib/lib?.so;./lib?.so;./lib/?.so;");
```

**Comment by dboltovskyi** [comment]
Another approach could be to build `libbson4lua.so` instead of `bson4lua.so` in https://github.com/smartdevicelink/bson_c_lib/pull/35
In this case we don't need to update `./src/lua_interpreter.cc` and `018_V5_happy_path_SUCCESS.lua` script

**Comment by jacobkeeler** [comment]
@dboltovskyi Fixed the library search patterns

**Comment by dboltovskyi** [comment]
@jacobkeeler Thank you for the update - it works. 
However did you have a chance to check latest develop? It has [#189](https://github.com/smartdevicelink/sdl_atf/pull/189) fix merged and now all the libraries are built into `./atf_build/bin/lib` folder by default. 

We have some concerns regarding usage of `/usr/local/lib` folder to store SDL/ATF dependencies. There are a few reasons for that:
1. Ability to have sandboxed environment.
Having all SDL/ATF 3rd party libraries in a specific folder allows them to be easily uploaded to VM or Docker container. 
So we don't need to filter out non-SDL libs from `/usr/local/lib` folder.
2. Ability to have clean SDL/ATF build. 
Sometimes there could be changes introduced in 3rd party libs so they needs to be rebuilt. 
To be completely sure if we do not use old versions the easiest way is to delete one specific folder with all SDL/ATF libs and to rebuilt them from scratch.

**Comment by jacobkeeler** [comment]
@dboltovskyi Understood. This PR doesn't require that the library be in the `usr/local/lib` directory, so there should be no problem there. I also think that adding the `bin` suffix to the install directory will not have any effect on this PR, and this change is already merged into this branch.

**Pull request merged**
