### PR TITLE
Fix expired timeout issue

### PR DESCRIPTION
**Pull request by OHerasym**
### PR Changes

Add to timeout 500 ms to avoid a lot of adding timeouts in test scripts.

Related: [APPLINK-24879](https://adc.luxoft.com/jira/browse/APPLINK-24879)

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review: @Kozoriz, @LuxoftAKutsan , @dtrunov

**Comment by Kozoriz** [comment]
Reviewed

**Comment by dtrunov** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Pull request merged**
