### PR TITLE
Fix softButtonCapabilities according to requirements

### PR DESCRIPTION
**Pull request by OHerasym**
### PR Changes:
- Change softButtonCapabilities to object to array

Related: [APPLINK-26295](https://adc.luxoft.com/jira/browse/APPLINK-26295)

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review: @anosach-luxoft , @LuxoftAKutsan , @Kozoriz, @dtrunov,

**Comment by dtrunov** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Pull request merged**
