### PR TITLE
Update COMMITTERS.md file

### PR DESCRIPTION
**Pull request by VVeremjova**
Please review @AGritsevich, @dtrunov, @pvvasilev, @OHerasym 

Related to [APPLINK-27852](https://adc.luxoft.com/jira/browse/APPLINK-27852)

### CODE REVIEW

**Comment by pestOO** [comment]
@VVeremjova,
1. How to find a ticket you now implementing with this PR?
2. Is it forbidden to post Jira ticket till now?

**Comment by AGritsevich** [comment]
@VVeremjova, Reviewed.

**Comment by VVeremjova** [comment]
@pestOO Updated comment

**Comment by pestOO** [comment]
@VVeremjova,
What's about 2d question?

**Comment by VVeremjova** [comment]
@pestOO You can add Jira ticket In commit message, but information about adding should not be inside any documents. Officially there should not be any mentions about internal links

**Comment by OHerasym** [comment]
Reviewed.

**Comment by pvvasilev** [comment]
@VVeremjova Reviewed.

**Comment by pestOO** [comment]
Reviewed

**Pull request merged**
