### PR TITLE
Add SAVED result code to hmi_connection

### PR DESCRIPTION
**Pull request by OHerasym**
PR Changes:
- Add SAVED result code to hmi_connection

Related: [APPLINK-27448](https://adc.luxoft.com/jira/browse/APPLINK-27448)

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review ASAP: @anosach-luxoft , @LuxoftAKutsan , @orhan-mehmedov, @dtrunov

**Comment by dtrunov** [comment]
@OHerasym Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by orhan-mehmedov** [comment]
OHerasym Reviewed.

**Pull request merged**
