### PR TITLE
Make ATF work with BULK DATA

### PR DESCRIPTION
**Pull request by VVeremjova**
ATF should process bulk data messages

Relates to APPLINK-22712

Please review @OHerasym @dtrunov @Kozoriz @VProdanov

### CODE REVIEW

**Comment by VProdanov** [comment]
Reviewed

**Comment by dtrunov** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by OHerasym** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
reviewed

**Comment by LuxoftAKutsan** [comment]
@pestOO  of @AGaliuzov  please merge

**Pull request merged**
