### PR TITLE
Use newer version of json4lua

### PR DESCRIPTION
**Pull request by VVeremjova**
Related issue : APPLINK-16812

Please review @OHerasym, @nk0leg, @dtrunov, @okozlovlux, @LevchenkoS

### CODE REVIEW

**Comment by dtrunov** [comment]
Reviewed

**Comment by LevchenkoS** [comment]
@VVeremjova Reviewed

**Comment by OHerasym** [comment]
Reviewed

**Comment by okozlovlux** [comment]
@VVeremjova reviewed

**Comment by nk0leg** [comment]
Reviewed

**Pull request merged**
